@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(unregisteredUser, "Незарегистрированный пользователь", "Отсутствуют личные данные в системе")
Person(client, "Клиент", "Пользователь, зарегистрированный в системе, способный совершать заказы")
Person(provider, "Арендадатель", "Пользователь, зарегистрированнный в системе вместе с автомобилем, сдающимся в аренду")
Person(administrator, "Администратор", "Управление учетными записями, формирование отчетов, решение жалоб")
Person(systemAdministrator, "Системный администратор", "Поддержание работы информационной системы, безопасности данных")

System(system, "Система заказа авто", "Выбор наиболее подходящего транспорта для клиента")
System_Ext(navigationSystem, "Навигационная система", "Предоставление необходимых геоданных")
System_Ext(bankingSystem, "Банковская система", "Списание денежных средств клиента")
System_Ext(BrokerSystem, "Тех.поддержка", "Посредничество в работе с пользователями")

unregisteredUser --> system: Регистрируется в системе в качестве клиента либо арендадателя
client --> system: Выбирает параметры авто вместе с другими доступными опциями поездки и заказывает т/с
provider ---> system: Предоставляет авто сервису
administrator --> system: Решает спорные ситуации, проверяет водителей и транспортные средства
systemAdministrator --> system: Следит за целостностью системы и безопасностью данных в ней

system --> navigationSystem: Отслеживает т/с, маршрут поездки, его время.
system --> bankingSystem: Списывает денежные средства клиента
system --> BrokerSystem: Переводит заработанные деньги

SHOW_LEGEND()
@enduml
