@startuml maintenance
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


package "Разработка" {
    folder "Разработчики" {
        actor "Разработчик-Фронтендер"
        actor "Разработчик-Бэкендер"
    }
    actor "Devops"

    folder "CI/CD конвейер Github Actions" {
        folder "Базовый конвейер для фронтенд-сабмодуля и конкретных бэкенд-сабмодулей" {
            component "коммит на feature/* ветку"
            component "линтирование-сборка проекта проверка"
            component "обзор кода"
            component "мердж в develop ветку"
            component "ручное тестирование работоспособности"
            component "мердж в release ветку"
            component "сборка и пуш docker-образа в docker hub"

            [коммит на feature/* ветку] -> [линтирование-сборка проекта проверка]
            [линтирование-сборка проекта проверка] -> [обзор кода]
            [обзор кода] -> [мердж в develop ветку]
            [мердж в develop ветку] -> [ручное тестирование работоспособности]
            [ручное тестирование работоспособности] -> [мердж в release ветку]
            [мердж в release ветку] -> [сборка и пуш docker-образа в docker hub]
        }

        folder "Конвейер для (фронтенд|бэкенд)-сабмодуля внутри главного репозитория проекта" {
            component "коммит на develop"
            component "ручное тестирование работоспособности всего проекта"
            component "мердж в release ветку главного репо"
            component "деплой на удалённой машине через ssh-соединение к гитхабу"

            [коммит на develop] -> [ручное тестирование работоспособности всего проекта]
            [ручное тестирование работоспособности всего проекта] -> [мердж в release ветку главного репо]
            [мердж в release ветку главного репо] -> [деплой на удалённой машине через ssh-соединение к гитхабу]
        }

        folder "Конвейер для одного из бэкенд-сабмодулей внутри главного бэкенда-самбодуля" {
            component "коммит на develop бэкенд-сбмодуля"
            component "ручное тестирование работоспособности всего бэкенда"
            component "мердж в release ветку бэкенд-сабмодуля"
            component "сборка и пуш docker-образа бэкенд-самбодуля в docker hub"

            [коммит на develop бэкенд-сбмодуля] -> [ручное тестирование работоспособности всего бэкенда]
            [ручное тестирование работоспособности всего бэкенда] -> [мердж в release ветку бэкенд-сабмодуля]
            [мердж в release ветку бэкенд-сабмодуля] -> [сборка и пуш docker-образа бэкенд-самбодуля в docker hub]
            [сборка и пуш docker-образа бэкенд-самбодуля в docker hub] -> [Конвейер для (фронтенд|бэкенд)-сабмодуля внутри главного репозитория проекта]
        }
    }

    [Разработчик-Фронтендер] --> [Базовый конвейер для фронтенд-сабмодуля и конкретных бэкенд-сабмодулей] : "Разработка фичи"
    [Разработчик-Бэкендер] --> [Конвейер для одного из бэкенд-сабмодулей внутри главного бэкенда-самбодуля] : "Разработка фичи"
    [Devops] -> [CI/CD конвейер Github Actions] : "Поддержка CI пайплайна"
    [Devops] --> [Конвейер для (фронтенд|бэкенд)-сабмодуля внутри главного репозитория проекта] : "Поддержка CD пайплайна"

    [деплой на удалённой машине через ssh-соединение к гитхабу] --> [Мониторинг]
    [сборка и пуш docker-образа в docker hub] --> [Мониторинг]
    [сборка и пуш docker-образа бэкенд-самбодуля в docker hub] --> [Мониторинг]

    [Мониторинг] --> [Отзыв]
    [Отзыв] --> [Анализ требований]
    [Анализ требований] --> [Задача]

    [Разработчики] --> [Задача]
}

@enduml