@startuml

|Пользователь|

start
:Пользователь ввел свои данные;
if (Данные корректны?) then (Да)
    :завершить регистрацию;
else (нет)
    :отказать в регистрации;
endif
:Пользователь заказал авто;    
if (Автомобиль найден?) then (Да)
        :Дойти до автомобиля;
        :Начать аренду;
        :Начать поездку;
else (Нет)
    :Показать другие возможные автомобили;
    if (Автомобиль найден?) then (Да)
    else (Нет)
    :Отменить заказ;
    stop
    endif
endif
:Прибыть на место назначения;
:Запросить оплату по счетчику;
if (Водитель провел поездку без нарушений?) then (Да)
    else (Нет)
        :Заблокировать пользователя;
endif
:Завершить поездку;
stop

@enduml